<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="jakarta.tags.core" prefix="c" %>
<c:if test="${empty sessionScope.userRole || sessionScope.userRole != 'owner'}">
    <c:redirect url="login.jsp"/>
</c:if>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Rent4Student | Property Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        /* This hides all the website UI elements and formats the page perfectly for A4 printing */
        @media print {
            body { background-color: white !important; margin: 0; padding: 0; }
            .no-print { display: none !important; }
            .print-container { 
                box-shadow: none !important; 
                border: none !important; 
                width: 100% !important; 
                max-width: 100% !important; 
                padding: 0 !important;
                margin: 0 !important;
            }
            @page { margin: 2cm; }
        }
    </style>
</head>
<body class="bg-slate-100 font-sans text-slate-800 min-h-screen py-10">

    <!-- Top Action Bar (Hidden during print) -->
    <div class="max-w-4xl mx-auto px-6 mb-6 flex justify-between items-center no-print">
        <a href="properties" class="text-slate-500 hover:text-slate-800 font-bold flex items-center gap-2 transition-colors">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>
            Back to Properties
        </a>
        <button onclick="window.print()" class="bg-slate-900 hover:bg-slate-800 text-white font-bold py-3 px-6 rounded-xl shadow-lg transition-all flex items-center gap-2">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
            Print Official Report
        </button>
    </div>

    <!-- The Report Document -->
    <div class="print-container max-w-4xl mx-auto bg-white p-12 rounded-3xl shadow-xl border border-slate-200">
        
        <!-- Header -->
        <div class="flex justify-between items-start border-b-2 border-slate-900 pb-8 mb-8">
            <div>
                <h1 class="text-4xl font-black text-slate-900 tracking-tight uppercase">Property Performance Report</h1>
                <p class="text-slate-500 mt-2 font-medium">Rent4Student Management System</p>
            </div>
            <div class="text-right">
                <p class="text-sm font-bold text-slate-400 uppercase tracking-widest">Date Generated</p>
                <p class="text-lg font-black text-slate-900" id="currentDate"></p>
                <p class="text-sm font-bold text-slate-400 uppercase tracking-widest mt-2">Generated By</p>
                <p class="text-md font-bold text-slate-900">${sessionScope.loggedUser.fullName}</p>
            </div>
        </div>

        <!-- Property Details Section -->
        <div class="mb-10">
            <h2 class="text-xs font-black text-slate-400 uppercase tracking-widest mb-4">Target Asset</h2>
            <div class="bg-slate-50 rounded-2xl p-6 border border-slate-100 flex items-center justify-between">
                <div>
                    <h3 class="text-2xl font-black text-slate-900">${property.propertyName}</h3>
                    <p class="text-slate-500 font-medium mt-1 flex items-center gap-2">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
                        ${property.address}
                    </p>
                </div>
                <div class="text-right">
                    <span class="bg-slate-200 text-slate-700 font-black text-xs px-3 py-1 rounded-full uppercase tracking-widest">${property.propertyType}</span>
                </div>
            </div>
        </div>

        <!-- Financial & Usage Stats -->
        <h2 class="text-xs font-black text-slate-400 uppercase tracking-widest mb-4">Lifetime Analytics</h2>
        <div class="grid grid-cols-2 gap-6 mb-12">
            
            <div class="border-2 border-emerald-100 bg-emerald-50/30 rounded-2xl p-8 text-center">
                <div class="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-4">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                </div>
                <p class="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Total Revenue Gained</p>
                <h3 class="text-4xl font-black text-emerald-600">RM ${totalRevenue != null ? totalRevenue : '0.00'}</h3>
            </div>
            
            <div class="border-2 border-blue-100 bg-blue-50/30 rounded-2xl p-8 text-center">
                <div class="w-12 h-12 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center mx-auto mb-4">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>
                </div>
                <p class="text-sm font-bold text-slate-500 uppercase tracking-wider mb-1">Total Tenants Hosted</p>
                <h3 class="text-4xl font-black text-blue-600">${totalTenants != null ? totalTenants : '0'} Students</h3>
            </div>

        </div>

        <!-- Footer -->
        <div class="text-center pt-8 border-t border-slate-200 mt-auto">
            <p class="text-xs font-bold text-slate-400">Document internally verified and generated by Rent4Student algorithms.</p>
            <p class="text-xs text-slate-400 mt-1">&copy; 2026 Rent4Student. All rights reserved.</p>
        </div>

    </div>

    <!-- Script to set today's date automatically -->
    <script>
        const dateOptions = { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' };
        document.getElementById('currentDate').innerText = new Date().toLocaleDateString('en-MY', dateOptions);
    </script>
</body>
</html>